<?php

namespace app\index\controller;

use think\Controller;
use app\common\model\Address as AddressModel;
class Address extends Commen {
    /*
     * 没有登录去登录
     */
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->goin();
    }

    public function index(AddressModel $address){
        if(request()->isPost()){
            $res=$address->store(input('post.'));
            if ($res['valid']){
                $this->redirect('index');
            }
        }
        //网页头部标题
        $title='Knock--收货地址';
        //地址
        $addressData=db('address')->where('address_uid',session('userid'))->select();
        //halt($addressData);
        return view('',compact('title','addressData'));
    }

    /*
     * 设置默认地址
     */
    public function setdefault(AddressModel $address){
        $id=input('param.id');
        $res=$address->setdefault($id);
        if($res['valid']){
            $this->redirect('index');
        }
    }

    /*
     * 编辑地址
     */
    public function edit(AddressModel $address){
        $id=input('param.id');
       if(request()->isPost()){
            $res=$address->edit(input('post.'));
            if($res['valid']){
                $this->redirect('index');
            }
        }
        //网页头部标题
        $title='Knock--收货地址';
        //地址
        $addressData=db('address')->where('address_uid',session('userid'))->select();
        //halt($addressData);
        $oldData=db('address')->where('address_id',$id)->find();
        //halt($oldData);
        return view('',compact('title','addressData','oldData'));
    }

    /*
     * 删除地址
     */
    public function del(){
        $id=input('get.id');
        //halt($id);
        if(AddressModel::destroy($id)){
            $this->redirect('index');
        }

    }
}
