<?php

namespace app\index\controller;

use think\Controller;
use app\common\model\Cart as CartModel;
class Cart extends Commen {
    /*
     * 没有登录去登录
     */
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->goin();
    }

    /*
     * 购物车页面
     */
    public function index(){
        //获得购物车里的数据
        $data=db('cart')->alias('c')
            ->join('attr a','c.cart_attrid=a.attr_id')
            ->join('goods g','a.attr_gid=g.goods_id')
            ->where('c.cart_uid',session('userid'))->select();
       // halt($data);
        $data=json_encode($data,JSON_UNESCAPED_UNICODE,JSON_UNESCAPED_SLASHES);
        //halt($data);
        //网页头部标题
        $title='Knock--购物车';
        return view('',compact('title','data'));
    }
    /*
     * 添加购物车
     */
    public function store(CartModel $cart){
        if(request()->isAjax()){
            $res=$cart->store(input('post.'));
            if($res['valid']){
                return 1;
            }else{
                return 0;
            }
        }
    }

    /*
     * 更改购物车商品属性的数量
     */
    public function num(CartModel $cart){
        $attr=$_GET;
        $res=$cart->num($attr);
        if($res){
            $this->redirect('index');
        }
    }

    /*
     * 更改购物车选中
     */
    public function checked(CartModel $cart){
        $data=$_GET;
        $res=$cart->checked($data);
        if($res){
            $this->redirect('index');
        }
    }

    /*
     * 删除购物车中的一组数据
     */
    public function del(){
        $id=input('get.id');
        if(CartModel::destroy($id)){
            $this->redirect('index');
        }
    }

    /*
     * 全选更改
     */
    public function allchecked(CartModel $cart){
        $data['cart_checked']=$_GET['allcheck'];
        $res=$cart->allchecked($data);
        if($res){
            $this->redirect('index');
        }
    }

    /*
     * 删除购物车中所有被选中的的商品
     */
    public function alldel(CartModel $cart){
        $res=$cart->alldel();
        if($res){
            $this->redirect('index');
        }
    }
}
