<?php

namespace app\index\controller;

use think\Controller;
use app\common\model\Order;
class Pay extends Commen{
    /*
    * 没有登录去登录
    */
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->goin();
    }

    /*
     * 支付页面
     */
    public function index(){
        //网页头部标题
        $title='Knock--支付';
        //订单数据
        $id=input('param.order_id');
        $data=db('order')->where('order_id',$id)->find();
        return view('',compact('title','data'));
    }

    /*
     * 支付成功后订单处理
     */
    public function handle(Order $order){
        $id=input('param.id');
        $data=[
            'order_paytime'=>time(),
            'order_pay'=>1,
            'order_id'=>$id
        ];
        $res=$order->handle($data);
        if($res['valid']){
            $this->redirect('index/pay/finish');
        }
    }

    /*
     * 支付成功
     */
    public function finish(){
        //网页头部标题
        $title='Knock--支付成功';
        return view('',compact('title'));
    }
}
